---
- name: "{{ (state | default('present') == 'present') | ternary('create', 'destroy') }} Azure RG & AKS cluster"
  hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AZURE_SUBSCRIPTION_ID: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    AZURE_SECRET: "{{ lookup('env', 'AZURE_SECRET') }}"
    AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"

  tasks:
    - name: "MS Teams - Starting cluster build"
      uri:
        url: "{{ webhook }}"
        method: POST
        headers: "'accept'='application/json'"
        body: '{"text": "{{ input_name }} : {{ lookup("pipe", "date") }} - START CLUSTER BUILD"}'
        body_format: json
        status_code: 200

    - name: "{{ (state | default('present') == 'present') | ternary('create', 'destroy') }} resource group {{ resource_group }}"
      azure_rm_resourcegroup:
        auth_source: "env"
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: "{{ state | default('present') }}"
        force: True
        tags:
          Environment: "AKS-Demo"

    - name: "{{ (state | default('present') == 'present') | ternary('create', 'destroy') }} managed AKS cluster {{ aks_name }}"
      azure_rm_aks:
        profile: "default"
        auth_source: "env"
        name: "{{ aks_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ aks_name }}"
        linux_profile:
          admin_username: "{{ username }}"
          ssh_key: "{{ ssh_key }}"
        service_principal:
          client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
          client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        agent_pool_profiles:
          - name: "default"
            count: "{{ vm_count }}"
            vm_size: "{{ vm_size }}"
        state: "present"
        tags:
          Environment: "AKS-Demo"
      register: aks
      when: state | default('present') == 'present'

#    - name: "Show output of AKS results"
#      debug:
#        var: aks
    - name: "MS Teams - Starting application build"
      uri:
        url: "{{ webhook }}"
        method: POST
        headers: "'accept'='application/json'"
        body: '{"text": "{{ input_name }} : {{ lookup("pipe", "date") }} - START APP BUILD"}'
        body_format: json
        status_code: 200

    - name: "Login to Azure"
      command: "/usr/bin/az login --service-principal -u {{ lookup('env', 'AZURE_CLIENT_ID') }} -p {{ lookup('env', 'AZURE_SECRET') }} --tenant {{ lookup('env', 'AZURE_TENANT') }}"
      register: az_login

    - name: "Download credentials"
      command: "/usr/bin/az aks get-credentials --resource-group {{ resource_group }} --name {{ aks_name }} --file {{ kube_conf }} --overwrite-existing"
      register: az_creds

    - name: "Show output of AKS results"
      debug:
        var: az_creds

#    - name: "Stat the file"
#      stat:
#        path: "{{ lookup('env', 'WORKSPACE')+'/files/azure-vote.yml' }}"
#      register: stat
#
#    - name: "Debug azure-vote.yml location"
#      debug:
#        var: stat
##        msg: "{{ lookup('env', 'WORKSPACE')+'/files/azure-vote.yml' }}"
#

    - name: "Run the app"
      command: "/usr/local/bin/kubectl --kubeconfig {{ kube_conf }} apply -f {{ app_file }}"
      register: az_runapp

    - debug: var=az_runapp
 
    - name: "Wait for allocation of app ip"
      command: "/usr/local/bin/kubectl --kubeconfig {{ kube_conf }} get service azure-vote-front"
      register: kubectl_get_service
      until: kubectl_get_service.stdout | regex_findall('\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b') | length == 2
      retries: 120
      delay: 5
      ignore_errors: True
 
    - name: "Debug kubectl_get_service"
      debug:
        var: kubectl_get_service
 
    - name: set fact
      set_fact:
        app_external_ip: "{{ kubectl_get_service.stdout  | regex_findall('\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b') | last }}"
 
    - debug: var=app_external_ip
 
    - name: "Create app dns name"
      azure_rm_dnsrecordset:
        resource_group: "cloud-msp.net"
        zone_name: "cloud-msp.net"
        state: "present"
        relative_name: "{{ input_name }}"
        time_to_live: 300
        record_type: "A"
        records:
          - entry: "{{ app_external_ip }}"
      ignore_errors: True

    - name: "Wait for app start on port 80"
      uri:
        url: "http://{{ app_external_ip }}:80"
        status_code: 200
        return_content: True
      register: result
      until: result.content | regex_search('(Azure Voting App)')
      retries: 60
      delay: 10

    - name: "MS Teams - Finished build"
      uri:
        url: "{{ webhook }}"
        method: POST
        headers: "'accept'='application/json'"
        body: '{"text": "{{ input_name }} : {{ lookup("pipe", "date") }} - FINISHED BUILD"}'
        body_format: json
        status_code: 200

